import { StyleSheet } from "react-native";
import { Theme } from "@/constants/Theme";
import { sheetMaxH } from "./constants";

export const invoiceReviewSheetStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  sheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#0d1526",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
    paddingBottom: 36,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 8,
  },
  content: {
    paddingHorizontal: 24,
    flex: 1,
  },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 24 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  docIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: "rgba(45, 212, 191, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(45, 212, 191, 0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  closeBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.05)",
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    color: "#fca5a5",
    fontFamily: "Outfit_500Medium",
    fontSize: 14,
    marginBottom: 12,
  },
  loadingBlock: {
    alignItems: "center",
    paddingVertical: 32,
    gap: 12,
  },
  loadingCaption: {
    fontSize: 14,
    fontFamily: "Outfit_500Medium",
    color: "#94a3b8",
  },
  vendor: {
    fontSize: 22,
    fontFamily: "Outfit_700Bold",
    color: "white",
    letterSpacing: -0.3,
    marginBottom: 6,
  },
  amount: {
    fontSize: 36,
    fontFamily: "Outfit_800ExtraBold",
    color: "#2dd4bf",
    letterSpacing: -1,
    marginBottom: 20,
  },
  detailGrid: {
    gap: 0,
    marginBottom: 20,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.04)",
  },
  detailLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  detailLabelText: {
    fontSize: 13,
    fontFamily: "Outfit_600SemiBold",
    color: "#64748b",
  },
  detailValue: {
    fontSize: 14,
    fontFamily: "Outfit_700Bold",
    color: "white",
  },
  viewOriginalBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 14,
    borderRadius: 16,
    marginBottom: 16,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  viewOriginalBtnText: {
    fontSize: 15,
    fontFamily: "Outfit_600SemiBold",
    color: "#e2e8f0",
  },
  linesSection: {
    marginBottom: 16,
  },
  linesSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  linesSectionTitle: {
    fontSize: 15,
    fontFamily: "Outfit_700Bold",
    color: "#e2e8f0",
  },
  linesHint: {
    fontSize: 12,
    fontFamily: "Outfit_500Medium",
    color: "#64748b",
    marginBottom: 12,
    lineHeight: 18,
  },
  lineCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  lineCardWarn: {
    borderColor: "rgba(251, 191, 36, 0.35)",
    backgroundColor: "rgba(251, 191, 36, 0.06)",
  },
  lineDesc: {
    fontSize: 15,
    fontFamily: "Outfit_600SemiBold",
    color: "white",
    marginBottom: 4,
  },
  lineAmt: {
    fontSize: 14,
    fontFamily: "Outfit_500Medium",
    color: "#94a3b8",
    marginBottom: 10,
  },
  hintRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
  },
  hintText: {
    fontSize: 12,
    fontFamily: "Outfit_600SemiBold",
    color: "#fbbf24",
  },
  linkPickerBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
  },
  linkPickerBtnText: {
    fontSize: 14,
    fontFamily: "Outfit_600SemiBold",
    color: "#e2e8f0",
    flex: 1,
  },
  linkPickerChevron: {
    fontSize: 10,
    color: "#94a3b8",
  },
  noLines: {
    fontSize: 13,
    fontFamily: "Outfit_500Medium",
    color: "#64748b",
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 20,
  },
  reviewDismissHint: {
    fontSize: 12,
    fontFamily: "Outfit_500Medium",
    color: "#64748b",
    lineHeight: 18,
    textAlign: "center",
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  saveBtn: {
    backgroundColor: Theme.colors.brand.primary,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 12,
  },
  saveBtnDisabled: { opacity: 0.7 },
  saveBtnText: {
    fontSize: 16,
    fontFamily: "Outfit_700Bold",
    color: "white",
  },
  deleteBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: "rgba(244, 63, 94, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(244, 63, 94, 0.15)",
  },
  deleteBtnText: {
    fontSize: 15,
    fontFamily: "Outfit_700Bold",
    color: "#f43f5e",
  },
  pickerRoot: {
    flex: 1,
    justifyContent: "flex-end",
  },
  pickerDim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  pickerSheet: {
    backgroundColor: "#f8fafc",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 16,
    paddingBottom: 28,
    maxHeight: sheetMaxH * 0.55,
  },
  pickerTitle: {
    fontSize: 17,
    fontFamily: "Outfit_700Bold",
    color: Theme.colors.text.primary,
    textAlign: "center",
    marginBottom: 8,
  },
  pickerList: { maxHeight: sheetMaxH * 0.4 },
  pickerRow: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.divider,
  },
  pickerRowText: {
    fontSize: 16,
    fontFamily: "Outfit_500Medium",
    color: Theme.colors.text.primary,
  },
  pickerCancel: {
    marginTop: 8,
    paddingVertical: 14,
    alignItems: "center",
  },
  pickerCancelText: {
    fontSize: 16,
    fontFamily: "Outfit_700Bold",
    color: Theme.colors.brand.primary,
  },
});
