import { StyleSheet } from "react-native";
import { Theme } from "@/constants/Theme";
import { sheetMaxH } from "./constants";

export const ledgerEntryReviewSheetStyles = StyleSheet.create({
  modalRoot: {
    flex: 1,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
  },
  sheet: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    width: "100%",
    height: sheetMaxH,
    maxHeight: sheetMaxH,
    backgroundColor: Theme.colors.card,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Theme.colors.divider,
    paddingBottom: 36,
    zIndex: 2,
    elevation: 12,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: Theme.colors.text.disabled,
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 8,
  },
  content: {
    paddingHorizontal: Theme.spacing.margin,
    flex: 1,
    minHeight: 0,
  },
  scroll: { flex: 1, minHeight: 0 },
  scrollContent: { paddingBottom: 32 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  headerTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  aiBadgeHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#fffbeb",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#fde68a",
  },
  aiTextHeader: {
    fontSize: 10,
    fontFamily: Theme.typography.family.black,
    color: "#d97706",
    textTransform: "uppercase",
  },
  docIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: `${Theme.colors.brand.primary}18`,
    borderWidth: 1,
    borderColor: `${Theme.colors.brand.primary}35`,
    justifyContent: "center",
    alignItems: "center",
  },
  closeBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: Theme.colors.inputBg,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.colors.divider,
  },
  errorText: {
    color: Theme.colors.status.error,
    fontFamily: Theme.typography.family.medium,
    fontSize: 14,
    marginBottom: 12,
  },
  loadingBlock: {
    alignItems: "center",
    paddingVertical: 32,
    gap: 12,
  },
  loadingCaption: {
    fontSize: 14,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.secondary,
  },
  verifyCallout: {
    flexDirection: "row",
    gap: 12,
    backgroundColor: "#fffbeb",
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#fde68a",
    marginBottom: 20,
  },
  verifyCalloutTextWrap: {
    flex: 1,
  },
  verifyCalloutTitle: {
    fontSize: 14,
    fontFamily: Theme.typography.family.bold,
    color: "#92400e",
    marginBottom: 2,
  },
  verifyCalloutDescription: {
    fontSize: 12,
    fontFamily: Theme.typography.family.medium,
    color: "#b45309",
    lineHeight: 18,
  },
  vendor: {
    fontSize: 22,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
    letterSpacing: -0.3,
    marginBottom: 6,
  },
  amount: {
    fontSize: 36,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.brand.primary,
    letterSpacing: -1,
    marginBottom: 20,
  },
  editableField: {
    marginBottom: 16,
  },
  editableLabel: {
    fontSize: 12,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.secondary,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 6,
    marginLeft: 4,
  },
  editableInput: {
    backgroundColor: Theme.colors.inputBg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.text.primary,
  },
  editableHint: {
    fontSize: 11,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.muted,
    lineHeight: 16,
    marginTop: 6,
    paddingHorizontal: 4,
  },
  editableInputMultiline: {
    minHeight: 80,
    textAlignVertical: "top",
    paddingTop: 12,
  },
  summaryBox: {
    flexDirection: "row",
    gap: 12,
    backgroundColor: "#f0fdfa",
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#ccfbf1",
    marginBottom: 20,
  },
  summaryText: {
    flex: 1,
    fontSize: 14,
    fontFamily: Theme.typography.family.medium,
    color: "#134e4a",
    lineHeight: 20,
  },
  summaryAnalyzing: {
    fontStyle: "italic",
    color: "#0d9488",
  },
  detailGrid: {
    gap: 0,
    marginBottom: 20,
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.colors.divider,
  },
  detailLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  detailLabelText: {
    fontSize: 13,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.text.secondary,
  },
  detailValue: {
    fontSize: 14,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
  },
  docTypeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.colors.divider,
    gap: 12,
  },
  docTypeRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  docTypeChange: {
    fontSize: 12,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.brand.primary,
  },
  viewOriginalBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 14,
    borderRadius: 16,
    marginBottom: 16,
    backgroundColor: Theme.colors.inputBg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  viewOriginalBtnText: {
    fontSize: 15,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.brand.primary,
  },
  linesSection: {
    marginBottom: 16,
  },
  linesSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  linesSectionTitle: {
    fontSize: 15,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
  },
  linesHint: {
    fontSize: 12,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.secondary,
    marginBottom: 12,
    lineHeight: 18,
  },
  scopeEmptyBanner: {
    padding: Theme.spacing.sm,
    borderRadius: Theme.radius.md,
    backgroundColor: `${Theme.colors.status.warning}14`,
    borderWidth: 1,
    borderColor: `${Theme.colors.status.warning}40`,
    marginBottom: 12,
  },
  scopeEmptyBannerText: {
    fontSize: 13,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.onSoft,
    lineHeight: 19,
  },
  lineCard: {
    backgroundColor: Theme.colors.inputBg,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: Theme.colors.divider,
  },
  lineCardWarn: {
    borderColor: `${Theme.colors.status.warning}55`,
    backgroundColor: `${Theme.colors.status.warning}10`,
  },
  lineDesc: {
    fontSize: 15,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.text.primary,
    marginBottom: 4,
  },
  lineAmt: {
    fontSize: 14,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.secondary,
    marginBottom: 10,
  },
  hintRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 10,
  },
  hintText: {
    fontSize: 12,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.status.warning,
  },
  linkPickerBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Theme.colors.card,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  linkPickerBtnDisabled: {
    opacity: 0.45,
  },
  linkPickerBtnText: {
    fontSize: 14,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.text.primary,
    flex: 1,
  },
  linkPickerChevron: {
    fontSize: 10,
    color: Theme.colors.text.muted,
  },
  noLines: {
    fontSize: 13,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.secondary,
    textAlign: "center",
    marginBottom: 16,
    lineHeight: 20,
  },
  reviewDismissHint: {
    fontSize: 12,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.muted,
    lineHeight: 18,
    textAlign: "center",
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  saveBtn: {
    backgroundColor: Theme.colors.brand.primary,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "center",
  },
  verifyBtn: {
    backgroundColor: "#d97706",
    borderColor: "#92400e",
    shadowColor: "#f59e0b",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  saveBtnDisabled: { opacity: 0.7 },
  saveBtnText: {
    fontSize: 16,
    fontFamily: Theme.typography.family.bold,
    color: "#ffffff",
  },
  deleteBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: `${Theme.colors.status.error}10`,
    borderWidth: 1,
    borderColor: `${Theme.colors.status.error}28`,
  },
  deleteBtnText: {
    fontSize: 15,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.status.error,
  },
  pickerOverlayRoot: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
    elevation: 30,
    justifyContent: "flex-end",
  },
  pickerRoot: {
    flex: 1,
    justifyContent: "flex-end",
  },
  pickerDim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
  },
  pickerSheet: {
    backgroundColor: Theme.colors.card,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 16,
    paddingBottom: 28,
    maxHeight: sheetMaxH * 0.55,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Theme.colors.divider,
  },
  pickerTitle: {
    fontSize: 17,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
    textAlign: "center",
    marginBottom: 8,
  },
  pickerList: { maxHeight: sheetMaxH * 0.4 },
  pickerRow: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Theme.colors.divider,
  },
  pickerRowText: {
    fontSize: 16,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.primary,
  },
  pickerCancel: {
    marginTop: 8,
    paddingVertical: 14,
    alignItems: "center",
  },
  pickerCancelText: {
    fontSize: 16,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.brand.primary,
  },
  originalPreviewHost: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 40,
    elevation: 40,
    backgroundColor: Theme.colors.background,
  },
});
