import { StyleSheet } from "react-native";
import { Theme } from "@/constants/Theme";
import { PROFILE_TAB_BAR_OFFSET } from "@/features/profile-tab/constants";

export const profileTabStyles = StyleSheet.create({
  header: {
    padding: Theme.spacing.xl,
    paddingBottom: Theme.spacing.xs,
  },
  title: {
    fontSize: Theme.typography.size.display,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.text.primary,
    letterSpacing: -1,
  },
  scrollContent: {
    padding: Theme.spacing.xl,
    /** Extra clearance so Sign out / Delete sit above the tab bar + home indicator. */
    paddingBottom: PROFILE_TAB_BAR_OFFSET + 80,
    gap: Theme.spacing.xxl,
  },
  sectionCard: {
    padding: Theme.spacing.lg,
    borderRadius: Theme.radius.xl,
  },
  sectionHeader: {
    fontSize: Theme.typography.size.xs,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.brand.primary,
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: Theme.spacing.lg,
  },
  inputGroup: {
    marginBottom: Theme.spacing.lg,
  },
  label: {
    fontSize: 12,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.text.muted,
    marginBottom: 8,
    paddingLeft: 4,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Theme.colors.inputBg,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.inputBorder,
    height: 56,
    paddingHorizontal: 16,
  },
  disabledInput: {
    backgroundColor: "rgba(255, 255, 255, 0.01)",
    borderColor: "transparent",
  },
  inputIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    color: Theme.colors.text.primary,
    fontSize: Theme.typography.size.lg,
    fontFamily: Theme.typography.family.medium,
  },
  saveButton: {
    marginTop: Theme.spacing.sm,
    height: 56,
  },
  duplicateSubBanner: {
    marginBottom: Theme.spacing.md,
    padding: 14,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.45)",
    backgroundColor: "rgba(245, 158, 11, 0.12)",
  },
  duplicateSubTitle: {
    fontSize: 14,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
    marginBottom: 6,
  },
  duplicateSubBody: {
    fontSize: 13,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.secondary,
    lineHeight: 20,
  },
  billingNote: {
    fontSize: 12,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.muted,
    lineHeight: 18,
    marginTop: Theme.spacing.md,
    paddingTop: Theme.spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Theme.colors.border,
  },
  planCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Theme.colors.inputBg,
    padding: 16,
    borderRadius: Theme.radius.lg,
    gap: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  architectPlanCard: {
    backgroundColor: "rgba(245, 158, 11, 0.04)",
    borderColor: "rgba(245, 158, 11, 0.2)",
    borderWidth: 1,
  },
  planIcon: {
    width: 44,
    height: 44,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.card,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  architectIcon: {
    backgroundColor: "rgba(245, 158, 11, 0.08)",
  },
  planInfo: {
    flex: 1,
  },
  planName: {
    fontSize: Theme.typography.size.lg,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.text.primary,
    letterSpacing: -0.3,
  },
  planStatus: {
    fontSize: Theme.typography.size.xs,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.secondary,
  },
  upgradeBtn: {
    backgroundColor: Theme.colors.brand.primary,
    paddingHorizontal: 16,
    minHeight: 44,
    paddingVertical: 10,
    borderRadius: Theme.radius.sm,
    justifyContent: "center",
    alignItems: "center",
  },
  upgradeText: {
    color: "white",
    fontSize: Theme.typography.size.sm,
    fontFamily: Theme.typography.family.bold,
  },
  settingItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.divider,
  },
  settingIcon: {
    width: 44,
    height: 44,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.inputBg,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    borderWidth: 1,
    borderColor: Theme.colors.divider,
  },
  settingTitle: {
    fontSize: Theme.typography.size.lg,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.text.primary,
  },
  settingSubtitle: {
    fontSize: Theme.typography.size.xs,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.secondary,
    marginTop: 2,
  },
  analyticsRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.divider,
    gap: 12,
  },
  dangerZone: {
    marginTop: 10,
    gap: 12,
  },
  dangerItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    backgroundColor: "rgba(244, 63, 94, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(244, 63, 94, 0.1)",
  },
  dangerText: {
    color: Theme.colors.status.error,
    fontSize: Theme.typography.size.md,
    fontFamily: Theme.typography.family.black,
    letterSpacing: 0.5,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
  },
  logoutText: {
    fontSize: Theme.typography.size.md,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.text.secondary,
  },
  versionText: {
    textAlign: "center",
    marginTop: 24,
    fontSize: Theme.typography.size.xs,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.muted,
    textTransform: "uppercase",
    letterSpacing: 2,
  },
});
