import { StyleSheet } from "react-native";
import { Theme } from "@/constants/Theme";
import { SnurraSize } from "@/components/ui/SnurraLoader";

export const analysisStyles = StyleSheet.create({
  analysisStepRoot: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
    paddingHorizontal: 28,
    width: "100%",
  },
  analysisLoaderCluster: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    minHeight: SnurraSize.hero + 24,
    marginBottom: 8,
  },
  analysisLoaderGlow: {
    position: "absolute",
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: "rgba(13, 148, 136, 0.07)",
  },
  analysisTitle: {
    fontSize: 26,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
    marginBottom: 6,
    letterSpacing: -0.5,
    textAlign: "center",
  },
  analysisLeadSubtitle: {
    fontSize: 16,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.secondary,
    textAlign: "center",
    lineHeight: 24,
    maxWidth: 320,
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  analysisSubtitle: {
    fontSize: 16,
    fontFamily: Theme.typography.family.medium,
    color: "#475569",
    textAlign: "center",
    lineHeight: 24,
    maxWidth: 320,
  },
  analysisMessageWrap: {
    minHeight: 52,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 8,
  },
  analysisProgressTrack: {
    position: "relative",
    marginTop: 20,
    width: "72%",
    maxWidth: 280,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(15, 23, 42, 0.08)",
    overflow: "hidden",
  },
  analysisProgressFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 3,
    backgroundColor: Theme.colors.brand.primary,
    shadowColor: "rgba(13, 148, 136, 0.45)",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.85,
    shadowRadius: 8,
    elevation: 2,
  },
  analysisFooterMicro: {
    marginTop: 12,
    fontSize: 10,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.text.muted,
    letterSpacing: 2,
    textAlign: "center",
    textTransform: "uppercase",
  },
  analysisChoiceIconWrap: {
    marginBottom: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  analysisChoiceBody: {
    fontSize: 15,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.secondary,
    textAlign: "center",
    lineHeight: 22,
    maxWidth: 340,
    marginBottom: 24,
    paddingHorizontal: 4,
  },
  analysisChoiceActions: {
    width: "100%",
    maxWidth: 320,
    gap: 10,
  },
  analysisChoiceBtn: {
    marginTop: 0,
  },
});
