import { StyleSheet } from "react-native";
import { Theme } from "@/constants/Theme";

export const estimateStyles = StyleSheet.create({
  estimateCard: {
    padding: 24,
    borderRadius: 32,
    alignItems: "stretch",
    width: "100%",
    backgroundColor: "white",
  },
  estimateHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 20,
  },
  estimateIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  confidenceBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "rgba(15, 23, 42, 0.06)",
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.colors.border,
  },
  confidenceText: {
    fontSize: 12,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.brand.deep,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  estimateLabel: {
    fontSize: 12,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.brand.deep,
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 8,
    textAlign: "center",
    alignSelf: "center",
    width: "100%",
  },
  estimateValue: {
    fontSize: 40,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.text.primary,
    letterSpacing: -1,
    marginBottom: 12,
    textAlign: "center",
  },
  estimateFallbackNotice: {
    fontSize: 13,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.onSoft,
    textAlign: "center",
    marginBottom: 12,
    lineHeight: 20,
    paddingHorizontal: 8,
    paddingVertical: 10,
    backgroundColor: "rgba(245, 158, 11, 0.12)",
    borderRadius: Theme.radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(245, 158, 11, 0.35)",
    alignSelf: "stretch",
  },
  estimateDisclaimer: {
    fontSize: 11,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.secondary,
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 16,
    opacity: 0.7,
  },
  estimateDivider: {
    width: "100%",
    height: 1,
    backgroundColor: "#f1f5f9",
    marginBottom: 24,
  },
  breakdown: {
    width: "100%",
    alignSelf: "stretch",
    gap: 12,
  },
  breakdownExpand: {
    overflow: "hidden",
    width: "100%",
    alignSelf: "stretch",
  },
  breakdownItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  breakdownText: {
    fontSize: 14,
    fontFamily: "Outfit_600SemiBold",
    color: "#475569",
  },
  scopeBreakdownContainer: {
    width: "100%",
    padding: 12,
    backgroundColor: "rgba(15, 23, 42, 0.03)",
    borderRadius: 14,
  },
  scopeLineList: {
    gap: 0,
  },
  scopeLineCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 10,
  },
  scopeLineCardBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(15, 23, 42, 0.06)",
  },
  scopeLineTextCol: {
    flex: 1,
    minWidth: 0,
  },
  scopeLineCategory: {
    fontSize: 13,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.text.primary,
  },
  scopeLineDesc: {
    fontSize: 12,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.secondary,
    marginTop: 4,
    lineHeight: 16,
  },
  scopeLineMeta: {
    fontSize: 11,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.muted,
    marginTop: 6,
  },
  scopeLineCost: {
    fontSize: 13,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
    marginTop: 2,
    flexShrink: 0,
    marginLeft: 8,
    minWidth: 108,
    textAlign: "right",
  },
  materialContainer: {
    marginTop: 16,
    padding: 12,
    backgroundColor: "rgba(15, 23, 42, 0.03)",
    borderRadius: 14,
    width: "100%",
  },
  materialHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  materialHeaderText: {
    fontSize: 10,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.text.secondary,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  materialGrid: {
    gap: 0,
    backgroundColor: "white",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.08)",
    overflow: "hidden",
  },
  materialTableHeader: {
    flexDirection: "row",
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: "rgba(15, 23, 42, 0.02)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(15, 23, 42, 0.06)",
  },
  materialTableLabel: {
    fontSize: 9,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.text.muted,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  materialTableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(15, 23, 42, 0.04)",
  },
  materialColMain: {
    flex: 3,
    paddingRight: 8,
  },
  materialColQty: {
    flex: 1.2,
    alignItems: "flex-end",
    paddingRight: 8,
  },
  materialColPrice: {
    flex: 1.2,
    alignItems: "flex-end",
  },
  materialNameTable: {
    fontSize: 12,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
  },
  materialBrandTable: {
    fontSize: 9,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.muted,
    marginTop: 2,
  },
  materialUnitTable: {
    fontSize: 11,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.primary,
  },
  materialPriceTable: {
    fontSize: 11,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
  },
  itemCountBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: "white",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.08)",
  },
  itemCountText: {
    fontSize: 10,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.muted,
  },
  materialQtyTable: {
    fontSize: 11,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.primary,
  },
  viewDetailsBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: "rgba(15, 23, 42, 0.05)",
    marginTop: 8,
  },
  activeViewDetailsBtn: {
    backgroundColor: Theme.colors.brand.primary,
  },
  viewDetailsText: {
    fontSize: 14,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.brand.deep,
  },
  activeViewDetailsText: {
    color: "white",
  },
});
