import { StyleSheet } from "react-native";
import { Theme } from "@/constants/Theme";

export const selectorStyles = StyleSheet.create({
  inputCard: {
    padding: 20,
    borderRadius: 24,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: Theme.colors.border,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  zipInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  zipTextInput: {
    flex: 1,
    height: 52,
    fontSize: 20,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
    paddingHorizontal: 12,
  },
  zipLocateButton: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "rgba(15, 23, 42, 0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  zipLocateButtonDisabled: {
    opacity: 0.5,
  },
  zipLocateHint: {
    fontSize: 13,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.secondary,
    marginTop: 16,
    textAlign: "center",
    lineHeight: 18,
    paddingHorizontal: 20,
  },
  iconGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 20,
  },
  iconCard: {
    width: "48%",
    aspectRatio: 1,
    padding: 16,
    borderRadius: 24,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: Theme.colors.border,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  iconCardActive: {
    borderColor: Theme.colors.brand.primary,
    backgroundColor: "rgba(13, 148, 136, 0.05)",
  },
  iconCircleBig: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(15, 23, 42, 0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  iconCircleBigActive: {
    backgroundColor: Theme.colors.brand.primary,
  },
  iconLabel: {
    fontSize: 14,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
    textAlign: "center",
  },
  iconLabelActive: {
    color: Theme.colors.brand.deep,
  },
  checkSeal: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Theme.colors.brand.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "white",
  },
  stageButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 20,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: Theme.colors.border,
    gap: 16,
  },
  stageButtonActive: {
    borderColor: Theme.colors.brand.primary,
    backgroundColor: "rgba(13, 148, 136, 0.05)",
  },
  stageIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "rgba(15, 23, 42, 0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  stageIconContainerActive: {
    backgroundColor: Theme.colors.brand.primary,
  },
  stageText: {
    fontSize: 16,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
  },
  stageTextActive: {
    color: Theme.colors.brand.deep,
  },
  stageDescription: {
    fontSize: 13,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.secondary,
    marginTop: 2,
  },
});
