import { StyleSheet } from "react-native";
import { Theme } from "@/constants/Theme";
import { SnurraSize } from "@/components/ui/SnurraLoader";

export const onboardingStyles = StyleSheet.create({
  screenColumn: {
    flex: 1,
  },
  stepScroll: {
    flex: 1,
  },
  stepScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 0,
    paddingBottom: 16,
  },
  privacyNote: {
    marginTop: 20,
    marginBottom: 8,
    fontSize: 12,
    lineHeight: 18,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.secondary,
    textAlign: "center",
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 4,
  },
  headerNavRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  iconGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 20,
  },
  iconCard: {
    width: "48%",
    aspectRatio: 1,
    backgroundColor: "white",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  iconCardActive: {
    borderColor: Theme.colors.brand.primary,
    borderWidth: 2,
    backgroundColor: Theme.colors.brand.primary + "05",
  },
  iconCircleBig: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  iconCircleBigActive: {
    backgroundColor: Theme.colors.brand.primary + "15",
  },
  iconLabel: {
    fontSize: 14,
    fontFamily: Theme.typography.family.black,
    color: "#64748b",
  },
  iconLabelActive: {
    color: Theme.colors.brand.primary,
  },
  checkSeal: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Theme.colors.brand.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
  },
  stageButton: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    backgroundColor: "white",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#f1f5f9",
    gap: 16,
  },
  stageButtonActive: {
    borderColor: Theme.colors.brand.primary,
    backgroundColor: Theme.colors.brand.primary + "05",
  },
  stageIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
  },
  stageIconContainerActive: {
    backgroundColor: Theme.colors.brand.primary + "15",
  },
  stageText: {
    flex: 1,
    fontSize: 15,
    fontFamily: Theme.typography.family.semibold,
    color: "#334155",
  },
  stageTextActive: {
    color: Theme.colors.brand.primary,
  },
  stageDescription: {
    fontSize: 13,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.secondary,
    marginTop: 4,
    lineHeight: 18,
  },
  progressSection: {
    marginTop: 16,
    width: "100%",
  },
  progressContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  phaseLabel: {
    marginTop: 10,
    fontSize: 12,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.text.secondary,
    textAlign: "center",
  },
  progressBar: {
    height: 4,
    borderRadius: 2,
    backgroundColor: "#e2e8f0",
  },
  progressBarActive: {
    backgroundColor: Theme.colors.brand.primary,
  },
  step5Column: {
    width: "100%",
  },
  stepTitle: {
    fontSize: 28,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.text.primary,
    marginBottom: 12,
    letterSpacing: -0.5,
  },
  stepSubtitle: {
    fontSize: 16,
    fontFamily: Theme.typography.family.regular,
    color: "#475569",
    marginBottom: 32,
    lineHeight: 24,
  },
  options: {
    gap: 12,
  },
  optionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    marginBottom: 12,
  },
  optionButtonActive: {
    backgroundColor: "rgba(13, 148, 136, 0.05)",
    borderColor: Theme.colors.brand.primary,
  },
  optionText: {
    fontSize: 16,
    fontFamily: "Outfit_600SemiBold",
    color: Theme.colors.text.primary,
  },
  optionTextActive: {
    color: Theme.colors.brand.primary,
  },
  inputCard: {
    padding: 4,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    paddingHorizontal: 20,
    height: 64,
  },
  input: {
    flex: 1,
    color: Theme.colors.text.primary,
    fontSize: 16,
    fontFamily: Theme.typography.family.medium,
  },
  textInput: {
    height: 64,
    paddingHorizontal: 20,
    fontSize: 28,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.text.primary,
    letterSpacing: 2,
  },
  zipInputRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 64,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    overflow: "hidden",
  },
  zipTextInput: {
    flex: 1,
    minHeight: 64,
    paddingLeft: 20,
    paddingRight: 8,
    fontSize: 28,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.text.primary,
    letterSpacing: 2,
  },
  zipLocateButton: {
    width: 52,
    height: 52,
    marginRight: 8,
    borderRadius: 16,
    backgroundColor: "rgba(13, 148, 136, 0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  zipLocateButtonDisabled: {
    opacity: 0.65,
  },
  zipLocateHint: {
    marginTop: 12,
    fontSize: 13,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.secondary,
    lineHeight: 18,
  },
  reviewCard: {
    padding: 24,
    borderRadius: 24,
  },
  reviewRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  reviewLabel: {
    fontSize: 14,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.secondary,
  },
  reviewValue: {
    fontSize: 16,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
  },
  footer: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(15, 23, 42, 0.08)",
    backgroundColor: "rgba(255, 255, 255, 0.72)",
  },
  visionContainer: {
    flex: 1,
  },
  visionActions: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 24,
  },
  visionButton: {
    flex: 1,
    padding: 24,
    borderRadius: 24,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    alignItems: "center",
  },
  visionIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  visionLabel: {
    fontSize: 14,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
  },
  visionHint: {
    fontSize: 12,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.secondary,
    marginTop: 4,
  },
  visionAsset: {
    width: 32,
    height: 32,
  },
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 24,
  },
  photoThumb: {
    width: 60,
    height: 60,
    borderRadius: 12,
    backgroundColor: "#f1f5f9",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    overflow: "hidden",
  },
  photoRemoveOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
  },
  scopeInputCard: {
    padding: 16,
    borderRadius: 20,
  },
  scopeInput: {
    minHeight: 120,
    color: Theme.colors.text.primary,
    fontSize: 16,
    fontFamily: Theme.typography.family.regular,
    textAlignVertical: "top",
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  loadingSpinner: {
    marginBottom: 32,
  },
  analysisStepRoot: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
    paddingHorizontal: 28,
    width: "100%",
  },
  analysisChoiceIconWrap: {
    marginBottom: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  analysisChoiceBody: {
    fontSize: 15,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.secondary,
    textAlign: "center",
    lineHeight: 22,
    maxWidth: 340,
    marginBottom: 24,
    paddingHorizontal: 4,
  },
  analysisChoiceActions: {
    width: "100%",
    maxWidth: 320,
    gap: 10,
  },
  analysisChoiceBtn: {
    marginTop: 0,
  },
  analysisLoaderCluster: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    minHeight: SnurraSize.hero + 24,
    marginBottom: 8,
  },
  analysisLoaderGlow: {
    position: "absolute",
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: "rgba(13, 148, 136, 0.07)",
  },
  analysisTitle: {
    fontSize: 26,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
    marginBottom: 6,
    letterSpacing: -0.5,
    textAlign: "center",
  },
  analysisLeadSubtitle: {
    fontSize: 16,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.secondary,
    textAlign: "center",
    lineHeight: 24,
    maxWidth: 320,
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  analysisSubtitle: {
    fontSize: 16,
    fontFamily: Theme.typography.family.medium,
    color: "#475569",
    textAlign: "center",
    lineHeight: 24,
    maxWidth: 320,
  },
  analysisMessageWrap: {
    minHeight: 52,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 8,
  },
  analysisProgressTrack: {
    position: "relative",
    marginTop: 20,
    width: "72%",
    maxWidth: 280,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(15, 23, 42, 0.08)",
    overflow: "hidden",
  },
  analysisProgressFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 3,
    backgroundColor: Theme.colors.brand.primary,
    shadowColor: "rgba(13, 148, 136, 0.45)",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.85,
    shadowRadius: 8,
    elevation: 2,
  },
  analysisFooterMicro: {
    marginTop: 12,
    fontSize: 10,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.text.muted,
    letterSpacing: 2,
    textAlign: "center",
    textTransform: "uppercase",
  },
  skipContainer: {
    marginTop: 32,
    alignItems: "center",
  },
  skipButton: {
    padding: 12,
  },
  skipText: {
    color: Theme.colors.text.secondary,
    fontSize: 14,
    fontFamily: Theme.typography.family.medium,
    textDecorationLine: "underline",
  },
  estimateCard: {
    padding: 24,
    borderRadius: 32,
    alignItems: "stretch",
    width: "100%",
  },
  estimateHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 20,
  },
  estimateIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 20,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  confidenceBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "rgba(15, 23, 42, 0.06)",
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.colors.border,
  },
  confidenceText: {
    fontSize: 12,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.brand.deep,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  estimateLabel: {
    fontSize: 12,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.brand.deep,
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 8,
    textAlign: "center",
    alignSelf: "center",
    width: "100%",
  },
  estimateValue: {
    fontSize: 40,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.text.primary,
    letterSpacing: -1,
    marginBottom: 12,
    textAlign: "center",
  },
  estimateFallbackNotice: {
    fontSize: 13,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.onSoft,
    textAlign: "center",
    marginBottom: 12,
    lineHeight: 20,
    paddingHorizontal: 8,
    paddingVertical: 10,
    backgroundColor: "rgba(245, 158, 11, 0.12)",
    borderRadius: Theme.radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(245, 158, 11, 0.35)",
    alignSelf: "stretch",
  },
  estimateDisclaimer: {
    fontSize: 11,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.secondary,
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 16,
    opacity: 0.7,
  },
  estimateDivider: {
    width: "100%",
    height: 1,
    backgroundColor: "#f1f5f9",
    marginBottom: 24,
  },
  breakdown: {
    width: "100%",
    alignSelf: "stretch",
    gap: 12,
  },
  breakdownExpand: {
    overflow: "hidden",
    width: "100%",
    alignSelf: "stretch",
  },
  breakdownItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  breakdownText: {
    fontSize: 14,
    fontFamily: "Outfit_600SemiBold",
    color: "#475569",
  },
  accountChoice: {
    gap: 16,
    marginTop: 20,
  },
  accountBtn: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    borderRadius: 20,
    backgroundColor: Theme.colors.brand.primary,
    gap: 16,
  },
  accountIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  accountBtnText: {
    fontSize: 18,
    fontFamily: Theme.typography.family.bold,
    color: "white",
  },
  badgeContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
  successBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: "rgba(16, 185, 129, 0.1)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(16, 185, 129, 0.2)",
  },
  successText: {
    fontSize: 12,
    fontFamily: Theme.typography.family.bold,
    color: "#10b981",
    textTransform: "uppercase",
  },
  scopeBreakdownContainer: {
    width: "100%",
    padding: 12,
    backgroundColor: "rgba(15, 23, 42, 0.03)",
    borderRadius: 14,
  },
  scopeLineList: {
    gap: 0,
  },
  scopeLineCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 10,
  },
  scopeLineCardBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(15, 23, 42, 0.06)",
  },
  scopeLineTextCol: {
    flex: 1,
    minWidth: 0,
  },
  scopeLineCategory: {
    fontSize: 13,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.text.primary,
  },
  scopeLineDesc: {
    fontSize: 12,
    fontFamily: Theme.typography.family.regular,
    color: Theme.colors.text.secondary,
    marginTop: 4,
    lineHeight: 16,
  },
  scopeLineMeta: {
    fontSize: 11,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.muted,
    marginTop: 6,
  },
  scopeLineCost: {
    fontSize: 13,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.primary,
    marginTop: 2,
    flexShrink: 0,
    marginLeft: 8,
    minWidth: 108,
    textAlign: "right",
  },
  materialContainer: {
    marginTop: 16,
    padding: 12,
    backgroundColor: "rgba(15, 23, 42, 0.03)",
    borderRadius: 14,
    width: "100%",
  },
  materialHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  materialHeaderText: {
    fontSize: 10,
    fontFamily: Theme.typography.family.black,
    color: Theme.colors.text.secondary,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  materialGrid: {
    gap: 8,
  },
  materialCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(15, 23, 42, 0.04)",
  },
  materialIconBg: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: Theme.colors.background,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  materialName: {
    fontSize: 13,
    fontFamily: Theme.typography.family.semibold,
    color: Theme.colors.text.primary,
  },
  materialMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 2,
  },
  brandTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  brandText: {
    fontSize: 10,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.brand.primary,
    textTransform: "uppercase",
  },
  materialQuantity: {
    fontSize: 10,
    fontFamily: Theme.typography.family.medium,
    color: Theme.colors.text.muted,
  },
  viewDetailsBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    marginTop: 12,
    borderRadius: 12,
    backgroundColor: "rgba(15, 23, 42, 0.03)",
    gap: 6,
    width: "100%",
  },
  activeViewDetailsBtn: {
    backgroundColor: "#134e4a",
  },
  viewDetailsText: {
    fontSize: 11,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.onSoft,
    textTransform: "uppercase",
  },
  activeViewDetailsText: {
    color: "white",
  },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(15, 23, 42, 0.08)",
  },
  dividerText: {
    color: Theme.colors.text.muted,
    fontFamily: Theme.typography.family.medium,
    fontSize: 12,
    marginHorizontal: 12,
  },
  handoffBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
  },
  handoffBtnText: {
    fontSize: 14,
    fontFamily: Theme.typography.family.bold,
    color: Theme.colors.text.secondary,
  },
});
